export const artImages = [
  {
    id: 1,
    src: '/images/fading_memories.jpg',
    alt: 'fading memories',
    category: 'mixmedia',
    updateTime: 'string',
  },
  {
    id: 2,
    src: '/images/shadow_impression_1.jpg',
    alt: 'shadow impression_1',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 3,
    src: '/images/shadow_impression_2.jpg',
    alt: 'shadow impression_2',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 4,
    src: '/images/shadow_impression_3.jpg',
    alt: 'shadow impression_3',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 5,
    src: '/images/shadow_impression_4.jpg',
    alt: 'shadow impression_4',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 6,
    src: '/images/shadow_impression_5.jpg',
    alt: 'shadow impression_5',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 7,
    src: '/images/shadow_impression_6.jpg',
    alt: 'shadow impression_6',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 8,
    src: '/images/Flower_Power_01.jpg',
    alt: 'Flower_Power_01',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 9,
    src: '/images/Flower_Power_02.jpg',
    alt: 'Flower_Power_02',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 10,
    src: '/images/Flower_Power_03.jpg',
    alt: 'Flower_Power_03',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 11,
    src: '/images/Flower_Power_04.jpg',
    alt: 'Flower_Power_04',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 12,
    src: '/images/Flower_Power_05.jpg',
    alt: 'Flower_Power_05',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 13,
    src: '/images/Flower_Power_06.jpg',
    alt: 'Flower_Power_06',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 14,
    src: '/images/Flower_Power_07.jpg',
    alt: 'Flower_Power_07',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 15,
    src: '/images/Flower_Power_08.jpg',
    alt: 'Flower_Power_08',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 16,
    src: '/images/Flower_Power_09.jpg',
    alt: 'Flower_Power_09',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 17,
    src: '/images/Flower_Power_10.jpg',
    alt: 'Flower_Power_10',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 18,
    src: '/images/Flower_Power_A.jpg',
    alt: 'Flower_Power_A',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 19,
    src: '/images/Flower_Power_B.jpg',
    alt: 'Flower_Power_B',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 20,
    src: '/images/Flower_Power_C.jpg',
    alt: 'Flower_Power_C',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 21,
    src: '/images/Flower_Power_D.jpg',
    alt: 'Flower_Power_D',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 22,
    src: '/images/Flower_Power_E.jpg',
    alt: 'Flower_Power_E',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 23,
    src: '/images/Flower_Power_F.jpg',
    alt: 'Flower_Power_F',
    category: '',
    updateTime: 'string',
  },
  {
    id: 24,
    src: '/images/revealing_shadows.jpg',
    alt: 'revealing_shadows',
    category: 'sculpture',
    updateTime: 'string',
  },
  {
    id: 25,
    src: '/images/sweet_dream.jpg',
    alt: 'sweet_dream',
    category: 'sculpture',
    updateTime: 'string',
  },
  {
    id: 26,
    src: '/images/water.jpg',
    alt: 'water',
    category: 'sculpture',
    updateTime: 'string',
  },
  ]