export const artImages = [
  {
    id: 1,
    src: '/images/fading_memories.jpg',
    alt: 'fading_memories',
    category: 'mixmedia',
    updateTime: 'string',
  },
  {
    id: 2,
    src: '/images/shadow_impression_01.jpg',
    alt: 'shadow_impression_01',
    category: 'mixmedia',
    updateTime: 'string',
  },
  {
    id: 3,
    src: '/images/shadow_impression_02.jpg',
    alt: 'shadow_impression_02',
    category: 'mixmedia',
    updateTime: 'string',
  },
  {
    id: 4,
    src: '/images/shadow_impression_03.jpg',
    alt: 'shadow_impression_03',
    category: 'mixmedia',
    updateTime: 'string',
  },
  {
    id: 5,
    src: '/images/shadow_impression_04.jpg',
    alt: 'shadow_impression_04',
    category: 'mixmedia',
    updateTime: 'string',
  },
  {
    id: 6,
    src: '/images/shadow_impression_05.jpg',
    alt: 'shadow_impression_05',
    category: 'mixmedia',
    updateTime: 'string',
  },
  {
    id: 7,
    src: '/images/shadow_impression_06.jpg',
    alt: 'shadow_impression_06',
    category: 'mixmedia',
    updateTime: 'string',
  },
  {
    id: 8,
    src: '/images/flower_power_01.jpg',
    alt: 'flower_power_01',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 9,
    src: '/images/flower_power_02.jpg',
    alt: 'flower_power_02',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 10,
    src: '/images/flower_power_03.jpg',
    alt: 'flower_power_03',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 11,
    src: '/images/flower_power_04.jpg',
    alt: 'flower_power_04',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 12,
    src: '/images/flower_power_05.jpg',
    alt: 'flower_power_05',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 13,
    src: '/images/flower_power_06.jpg',
    alt: 'flower_power_06',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 14,
    src: '/images/flower_power_07.jpg',
    alt: 'flower_power_07',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 15,
    src: '/images/flower_power_08.jpg',
    alt: 'flower_power_08',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 16,
    src: '/images/flower_power_09.jpg',
    alt: 'flower_power_09',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 17,
    src: '/images/flower_power_10.jpg',
    alt: 'flower_power_10',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 18,
    src: '/images/flower_power_A.jpg',
    alt: 'flower_power_A',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 19,
    src: '/images/flower_power_B.jpg',
    alt: 'flower_power_B',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 20,
    src: '/images/flower_power_C.jpg',
    alt: 'flower_power_C',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 21,
    src: '/images/flower_power_D.jpg',
    alt: 'flower_power_D',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 22,
    src: '/images/flower_power_E.jpg',
    alt: 'flower_power_E',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 23,
    src: '/images/flower_power_F.jpg',
    alt: 'flower_power_F',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 24,
    src: '/images/whispering_lights_01.jpg',
    alt: 'whispering_lights_01',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 25,
    src: '/images/whispering_lights_02.jpg',
    alt: 'whispering_lights_02',
    category: 'washi',
    updateTime: 'string',
  },
  {
    id: 26,
    src: '/images/whispering_lights_03.jpg',
    alt: 'whispering_lights_03',
    category: 'washi',
    updateTime: 'string',
  }
  ]