import Header from './components/Header'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Responsive nav',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"> 
      <body className="bg-[#FAF5F2]">
        <Header/>
        {children}
      </body>
    </html>
  )
}
