import Header from './components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { childrenProps } from './types/Interfaces'

export const metadata: Metadata = {
  title: 'Responsive nav',
  description: 'Generated by create next app',
}


const RootLayout: React.FC<childrenProps> = ({children}: childrenProps) => {
  return (
    <html lang="en"> 
      <body className="bg-[#FAF5F2]">
        <Header/>
        {children}
      </body>
    </html>
  )
}

export default RootLayout