import { PerformanceType } from "../types/Interfaces";

export const performanceData = [
      {
        id: 13,
        title: "Flower Dance - Spring",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime-Dance"],
        date: "Feb 2022",
        event: "A Night at the Eclipse",
        location: "Huntsville, ON",
        VideoId: "UUvLMgf1AQo",
      },
      {
        id: 12,
        title: "Life Cycle - Forest",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime-Dance"],
        date: "Sep 2021",
        event: "Dance Rx3",
        location: "Haliburton Sculpture Forest - Haliburton, ON",
        VideoId: "tmeCTB6XVDY",
      },
      {
        id: 11,
        title: "The Swan",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime-Dance"],
        date: "Mar 2021",
        event: "various",
        location: "online",
        VideoId: "RcDcS-j2vAQ",
      },
      {
        id: 10,
        title: "3-11-11",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime-Dance"],
        date: "Feb 2020",
        event: "Memories",
        location: "Tokyo, Japan",
        VideoId: "ZO7r9q7uGUA",
      },
      {
        id: 9,
        title: "untitled (improv)",
        subTitle: "",
        description: "",
        category: PerformanceType.Dance,
        date: "Feb 2020",
        event: "Memories",
        location: "Tokyo, Japan",
        VideoId: "8fMHokiuP9k",
      },
      {
        id: 8,
        title: "Washi",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime-Dance"],
        date: "Nov 2019",
        event: "The Promise of Sekishu exhibition closing",
        location: "Propeller Art Gallery - Toronto, ON",
        VideoId: "hqWZ2CwnR1g",
      },
      {
        id: 7,
        title: "Imprint",
        subTitle: "choreography by Meredith Thompson",
        description: "",
        category: PerformanceType.Dance,
        date: "Aug 2019",
        event: "Dusk Dances",
        location: "Withrow Park - Toronto, ON",
        VideoId: "sIBRHW4PH7U",
      },
      {
        id: 6,
        title: "Lotus Flower",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime-Dance"],
        date: "Mar 2019",
        event: "White Pavilions art installation by Yam Lau",
        location: "Varley Art Gallery - Markham, ON",
        VideoId: "16O66bu6p-k",
      },
      {
        id: 5,
        title: "The Funny Little Woman",
        subTitle: "",
        description: "",
        category: PerformanceType["Silent Storytelling"],
        date: "Jul 2003",
        event: "Atlin Arts & Music Festival",
        location: "Globe Theatre - Atlin, BC",
        VideoId: "vNERP66wJYc",
      },
      {
        id: 4,
        title: "Mime, Magic & Bubbles Show",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime/Clowning"],
        date: "May 2000",
        event: "Children's Own Museum",
        location: "McLaughlin Planetarium (ROM) - Toronto, ON",
        VideoId: "Vm7cS4pGkbc",
      },
      {
        id: 3,
        title: "Grandmother",
        subTitle: "",
        description: "",
        category: PerformanceType["Silent Storytelling"],
        date: "Feb 1996",
        event: "Toronto Storytelling Festival",
        location: "Harbourfront Centre - Toronto, ON",
        VideoId: "TuVsRLlZdbg",
      },

      {
        id: 2,
        title: "The Violinist",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime/Clowning"],
        date: "Feb 1996",
        event: "Homeworks",
        location: "Toronto, ON",
        VideoId: "0vBRcrmMUV4",
      },
      {
        id: 1,
        title: "TV Commercial",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime/Clowning"],
        date: "1990",
        event: "Hiroshima City - public education",
        location: "Hiroshima, Japan",
        VideoId: "XEi67heRyUQ",
      },
]