import { PerformanceType } from "../types/Interfaces";

export const performanceData = [
      {
        id: 13,
        title: "Flower Dance - Spring",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime-Dance"],
        date: "Feb 2022",
        event: "A Night at the Eclipse",
        location: "Huntsville, ON",
        url: "https://www.youtube.com/embed/UUvLMgf1AQo?si=0Nrik_qBYablyUDM",
      },
      {
        id: 12,
        title: "Life Cycle - Forest",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime-Dance"],
        date: "Sep 2021",
        event: "Dance Rx3",
        location: "Haliburton Sculpture Forest - Haliburton, ON",
        url: "https://www.youtube.com/embed/tmeCTB6XVDY?si=rDgjnY0IZLmE964X",
      },
      {
        id: 11,
        title: "The Swan",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime-Dance"],
        date: "Mar 2021",
        event: "various",
        location: "online",
        url: "https://www.youtube.com/embed/RcDcS-j2vAQ?si=JL89RgCRXRH-6Swb",
      },
      {
        id: 10,
        title: "3-11-11",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime-Dance"],
        date: "Feb 2020",
        event: "Memories",
        location: "Tokyo, Japan",
        url: "https://www.youtube.com/embed/ZO7r9q7uGUA?si=yAMqbHfwiDt07Kk2",
      },
      {
        id: 9,
        title: "untitled (improv)",
        subTitle: "",
        description: "",
        category: PerformanceType.Dance,
        date: "Feb 2020",
        event: "Memories",
        location: "Tokyo, Japan",
        url: "https://www.youtube.com/embed/8fMHokiuP9k?si=aXLYx7ma9yzvEqB7",
      },
      {
        id: 8,
        title: "Washi",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime-Dance"],
        date: "Nov 2019",
        event: "The Promise of Sekishu exhibition closing",
        location: "Propeller Art Gallery - Toronto, ON",
        url: "https://www.youtube.com/embed/hqWZ2CwnR1g?si=aLNNOy5zaFhG93K1",
      },
      {
        id: 7,
        title: "Imprint",
        subTitle: "choreography by Meredith Thompson",
        description: "",
        category: PerformanceType.Dance,
        date: "Aug 2019",
        event: "Dusk Dances",
        location: "Withrow Park - Toronto, ON",
        url: "https://www.youtube.com/embed/sIBRHW4PH7U?si=Sb7hrf5-soDhfRBM",
      },
      {
        id: 6,
        title: "Lotus Flower",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime-Dance"],
        date: "Mar 2019",
        event: "White Pavilions art installation by Yam Lau",
        location: "Varley Art Gallery - Markham, ON",
        url: "https://www.youtube.com/embed/16O66bu6p-k?si=Lws4HwJWHJHmMI0F",
      },
      {
        id: 5,
        title: "The Funny Little Woman",
        subTitle: "",
        description: "",
        category: PerformanceType["Silent Storytelling"],
        date: "Jul 2003",
        event: "Atlin Arts & Music Festival",
        location: "Globe Theatre - Atlin, BC",
        url: "https://www.youtube.com/embed/vNERP66wJYc?si=MkfvCc-YlFMG0quK",
      },
      {
        id: 4,
        title: "Mime, Magic & Bubbles Show",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime/Clowning"],
        date: "May 2000",
        event: "Children's Own Museum",
        location: "McLaughlin Planetarium (ROM) - Toronto, ON",
        url: "https://www.youtube.com/embed/Vm7cS4pGkbc?si=gq-i54EaH-bG-mH9",
      },
      {
        id: 3,
        title: "Grandmother",
        subTitle: "",
        description: "",
        category: PerformanceType["Silent Storytelling"],
        date: "Feb 1996",
        event: "Toronto Storytelling Festival",
        location: "Harbourfront Centre - Toronto, ON",
        url: "https://www.youtube.com/embed/TuVsRLlZdbg?si=-yxQGPJxBF-JfSfi",
      },

      {
        id: 2,
        title: "The Violinist",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime/Clowning"],
        date: "Feb 1996",
        event: "Homeworks",
        location: "Toronto, ON",
        url: "https://www.youtube.com/embed/0vBRcrmMUV4?si=SFPorToWsIAiZpdN",
      },
      {
        id: 1,
        title: "TV Commercial",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime/Clowning"],
        date: "1990",
        event: "Hiroshima City - public education",
        location: "Hiroshima, Japan",
        url: "https://www.youtube.com/embed/XEi67heRyUQ?si=oYq0GdrFT21xrkCF",
      },
]