import { PerformanceType } from "../types/Interfaces";

export const performanceData = [
      {
        id: 1,
        title: "Flower Dance - Spring",
        additionalTitle: "",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime-Dance"],
        event: "A Night at the Eclipse",
        location: "Huntsville ON",
        date: "Feb 2022",
        url: "https://www.youtube.com/embed/UUvLMgf1AQo?si=0Nrik_qBYablyUDM",
      },
      {
        id: 2,
        title: "Life Cycle - Forest",
        additionalTitle: "(excerpt)",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime-Dance"],
        date: "Sep 2021",
        event: "Dance Rx3",
        location: "Haliburton Sculpture Forest",
        url: "https://www.youtube.com/embed/tmeCTB6XVDY?si=rDgjnY0IZLmE964X",
      },
      {
        id: 3,
        title: "The Swan",
        additionalTitle: "",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime-Dance"],
        date: "various",
        event: "various",
        location: "various",
        url: "https://www.youtube.com/embed/RcDcS-j2vAQ?si=JL89RgCRXRH-6Swb",
      },
      {
        id: 4,
        title: "3-11-11",
        additionalTitle: "(excerpt)",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime-Dance"],
        date: "Feb 2020",
        event: "Memories",
        location: "Tokyo, Japan",
        url: "https://www.youtube.com/embed/ZO7r9q7uGUA?si=yAMqbHfwiDt07Kk2",
      },
      // {
      //   id: 5,
      //   title: "Washi",
      //   additionalTitle: "",
      //   subTitle: "",
      //   description: "",
      //   category: PerformanceType["Mime-Dance"],
      //   date: "Oct 2019",
      //   event: "Washi Sisters: A Journey exhibition opening",
      //   location: "Propeller Art Gallery - Toronto ON",
      //   url: "https://www.youtube.com/shorts/3TTvDzPwwTQ",
      // },
      {
        id: 6,
        title: "Lotus Flower",
        additionalTitle: "(excerpt)",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime-Dance"],
        date: "Mar 2019",
        event: "White Pavilions art installation by Yam Lau",
        location: "Varley Art Gallery - Markham ON",
        url: "https://www.youtube.com/embed/16O66bu6p-k?si=Lws4HwJWHJHmMI0F",
      },
      // {
      //   id: 7,
      //   title: "untitled (improv) (excerpt)",
      //   additionalTitle: "",
      //   subTitle: "",
      //   description: "",
      //   category: PerformanceType.Dance,
      //   date: "Feb 2020",
      //   event: "Memories",
      //   location: "Tokyo, Japan",
      //   url: "https://www.youtube.com/shorts/9iLvMyUgqgU",
      // },
      {
        id: 8,
        title: "Imprint",
        additionalTitle: "(excerpt)",
        subTitle: "(choreography by Meredith Thompson)",
        description: "",
        category: PerformanceType.Dance,
        date: "Aug 2019",
        event: "Dusk Dances",
        location: "Withrow Park - Toronto ON",
        url: "https://www.youtube.com/embed/sIBRHW4PH7U?si=Sb7hrf5-soDhfRBM",
      },
      {
        id: 9,
        title: "The Funny Little Woman",
        additionalTitle: "",
        subTitle: "",
        description: "",
        category: PerformanceType["Silent Storytelling"],
        date: "Jul 2003",
        event: "Atlin Arts & Music Festival",
        location: "Globe Theatre - Atlin BC",
        url: "https://www.youtube.com/embed/vNERP66wJYc?si=MkfvCc-YlFMG0quK",
      },
      {
        id: 10,
        title: "Grandmother",
        additionalTitle: "",
        subTitle: "",
        description: "",
        category: PerformanceType["Silent Storytelling"],
        date: "Feb 1996",
        event: "Toronto Storytelling Festival",
        location: "Harbourfront Centre - Toronto ON",
        url: "https://www.youtube.com/embed/TuVsRLlZdbg?si=-yxQGPJxBF-JfSfi",
      },
      {
        id: 11,
        title: "Mime, Magic & Bubbles Show",
        additionalTitle: "",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime/Clowning"],
        date: "May 2000",
        event: "Children's Own Museum",
        location: "McLaughlin Planetarium (ROM) - Toronto ON",
        url: "https://www.youtube.com/embed/Vm7cS4pGkbc?si=gq-i54EaH-bG-mH9",
      },
      {
        id: 12,
        title: "The Violinist",
        additionalTitle: "",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime/Clowning"],
        date: "Feb 1996",
        event: "Homeworks",
        location: "Toronto ON",
        url: "https://www.youtube.com/embed/0vBRcrmMUV4?si=SFPorToWsIAiZpdN",
      },
      {
        id: 13,
        title: "TV Commercial",
        additionalTitle: "",
        subTitle: "",
        description: "",
        category: PerformanceType["Mime/Clowning"],
        date: "1990",
        event: "Hiroshima City - public education",
        location: "Hiroshima, Japan",
        url: "https://www.youtube.com/embed/XEi67heRyUQ?si=oYq0GdrFT21xrkCF",
      },
]